### ISSUE TITLE
"Bad Request" when trying to POST any content

### ISSUE THREAD

**Issue by clarabez** [eliasnogueira/credit-api#26]
**Describe the issue**
I am able to GET content from service, but not to POST.

From Swagger:

`curl -X POST "http://localhost:8088/api/v1/simulations" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"cpf\": 065065065065, \"id\": 100, \"name\": \"Maria Clara\", \"email\": \"email@email.com\", \"amount\": 1200, \"installments\": 3, \"insurance\": true}"`

Output from Swagger, with 400 error code:

```
 connection: close 
 content-length: 0 
 date: Tue, 24 Nov 2020 13:58:57 GMT 
```

The same is being returned when using Postman.

**Steps**
Steps to reproduce the unexpected behaviour:
1. Go to: http://localhost:8088/swagger-ui.html#/Simulations/newSimulatorUsingPOST
2. Update content to any valid other.
3. Check output.

**Expected behaviour**
POST should work properly when service is active.

**Additional information**
N/A

**Comment by eliasnogueira** [comment]
Sorry for this long delay to replay you.
The BadRequest problem is happening because you are sending the `id` object, which is unique and must be removed from the response body.

The example value for the `simulation` body object doesn't have this attribute.
Also one thing to fix in your cURL request is that the `cpf` is a `string`, not a `number`.

**Comment by clarabez** [comment]
Perfect, Elias! thanks for you reply :)
I am closing this issue.
